describe("SwagLabs_Login", () => {
  it("tests SwagLabs_Login", () => {
    cy.viewport(1348, 953);
    cy.visit("https://www.saucedemo.com/v1/");
    cy.get("#login_credentials").dblclick();
    cy.get("#login_credentials").click();
    cy.get("[data-test='username']").click();
    cy.get("[data-test='username']").type("standard_user");
    cy.get("div.login_password").dblclick();
    cy.get("div.login_password").click();
    cy.get("[data-test='password']").dblclick();
    cy.get("[data-test='password']").type("secret_sauce");
    cy.get("#login-button").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/inventory.html");
    cy.get("div.inventory_container > div > div:nth-of-type(1) button").click();
    cy.get("path").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/cart.html");
    cy.get("a.btn_action").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/checkout-step-one.html");
    cy.get("#contents_wrapper").click();
    cy.get("[data-test='firstName']").click();
    cy.get("[data-test='firstName']").type("P");
    cy.get("[data-test='firstName']").type("Philip");
    cy.get("[data-test='lastName']").click();
    cy.get("[data-test='lastName']").type("O");
    cy.get("[data-test='lastName']").type("Odzor");
    cy.get("[data-test='postalCode']").click();
    cy.get("[data-test='postalCode']").type("00233");
    cy.get("div.checkout_buttons > input").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/checkout-step-two.html");
    cy.get("a.btn_action").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/checkout-complete.html");
    cy.get("path").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/cart.html");
    cy.get("a.btn_secondary").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/inventory.html");
    cy.get("#page_wrapper").click();
    cy.get("#menu_button_container div:nth-of-type(3) button").click();
    cy.get("chatgpt-sidebar").click();
    cy.get("#logout_sidebar_link").click();
    cy.location("href").should("eq", "https://www.saucedemo.com/v1/index.html");
  });
});
